# See https://github.com/google/mono_repo.dart for details on this file
dart:
- dev

stages:
- analyzer_and_format:
  - group:
    - dartfmt
    - dartanalyzer: --fatal-infos .
- unit_test:
  - test:
  - test: -p chrome
- ensure_build:
  - test: --run-skipped -t presubmit-only test/ensure_build_test.dart

cache:
  directories:
  - .dart_tool/build
